global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    scrape_timeout: 500ms
    static_configs:
      - targets: ['localhost:7799']
